# Generated by Django 5.2.17 on 2026-08-09 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Perfil')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(default='deepseek-v4-flash', help_text='ID do modelo no catálogo OpenCode Go (fallback: deepseek-v4-flash).', max_length=100)),
                ('default_max_iterations', models.PositiveSmallIntegerField(default=3)),
                ('default_max_budget_usd', models.DecimalField(decimal_places=4, default=2.5, max_digits=6)),
                ('default_max_time_seconds', models.PositiveIntegerField(default=300, help_text='Tempo máximo de execução em segundos (T_max)')),
            ],
            options={
                'verbose_name': 'Perfil de Geração',
                'verbose_name_plural': 'Perfis de Geração',
            },
        ),
        migrations.CreateModel(
            name='QualityAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Critério/Eixo')),
                ('weight', models.FloatField(default=1.0, help_text='Peso nominal. Será normalizado automaticamente (sum w_i = 1.0) no cálculo.', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('base_score', models.FloatField(default=100.0, help_text='Pontuação total do critério antes das deduções.', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('deduction_rules', models.TextField(help_text='Subprompt injetado para o Corretor detalhando as regras de penalização.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='profiles.profileconfig')),
            ],
            options={
                'verbose_name': 'Eixo de Qualidade',
                'verbose_name_plural': 'Eixos de Qualidade',
                'constraints': [models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='check_axis_weight_positive'), models.CheckConstraint(condition=models.Q(('base_score__gt', 0)), name='check_axis_base_score_positive')],
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(choices=[('WRITER', 'Agente Redator'), ('GUARDRAIL', 'Agente Guard-rail (Fidelidade)'), ('AUDITOR', 'Corretor Base (Tribunal)')], max_length=50)),
                ('content', models.TextField(help_text='Diretriz de sistema principal do Agente.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='profiles.profileconfig')),
            ],
            options={
                'verbose_name': 'Prompt do Sistema',
                'verbose_name_plural': 'Prompts do Sistema',
                'constraints': [models.UniqueConstraint(fields=('profile', 'role_type'), name='unique_role_per_profile')],
            },
        ),
    ]
