# Generated by Django 5.2.17 on 2026-08-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconfig',
            name='default_max_time_seconds',
            field=models.PositiveIntegerField(default=600, help_text='Tempo máximo de execução em segundos (T_max)'),
        ),
    ]
