# Generated by Django 5.2.17 on 2026-08-09 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em Execução'), ('COMPLETED', 'Concluído com Sucesso'), ('COMPLETED_WITH_ROLLBACK', 'Concluído com Rollback (Melhor Snapshot)'), ('ABORTED_GUARDRAIL_STRIKES', 'Abortado - Falha Crítica Guard-rail (3 Strikes)'), ('FAILED_BUDGET_EXCEEDED', 'Falha - Orçamento Excedido'), ('FAILED_TIMEOUT', 'Falha - Tempo Limite Excedido'), ('FAILED_NO_SNAPSHOTS', 'Falha - Estagnado sem Snapshots')], default='PENDING', max_length=50)),
                ('original_prompt', models.TextField(help_text='Mensagem inicial do usuário')),
                ('current_iteration', models.PositiveSmallIntegerField(default=1)),
                ('current_step', models.CharField(blank=True, help_text='Progresso descritivo para HTMX', max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp exato em que a task mudou de PENDING para RUNNING.', null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Último sinal de vida do Worker. Atualizado a cada transição de step.', null=True)),
                ('max_iterations', models.PositiveSmallIntegerField(default=3)),
                ('max_budget_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('max_time_seconds', models.PositiveIntegerField(help_text='Tempo limite copiado do perfil no momento da criação')),
                ('accumulated_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('accumulated_completion_tokens', models.PositiveIntegerField(default=0)),
                ('accumulated_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('final_text', models.TextField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, help_text='Pontuação Global W(x) atingida', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='profiles.profileconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicraft_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Tarefa',
                'verbose_name_plural': 'Execuções de Tarefa',
            },
        ),
        migrations.CreateModel(
            name='ExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iteration_number', models.PositiveSmallIntegerField()),
                ('generated_text', models.TextField()),
                ('nash_score', models.FloatField(help_text='Score Global consolidado [0.01, 1.0]')),
                ('normalized_scores', models.JSONField(default=dict)),
                ('cycle_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='orchestrator.taskexecution')),
            ],
            options={
                'verbose_name': 'Snapshot de Iteração',
                'verbose_name_plural': 'Snapshots de Iteração',
            },
        ),
        migrations.CreateModel(
            name='AuditorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor_type', models.CharField(choices=[('CORRETOR_1', 'Corretor Paralelo 1'), ('CORRETOR_2', 'Corretor Paralelo 2'), ('DESEMPATE', 'Corretor de Desempate (3º)')], max_length=50)),
                ('deductions_payload', models.JSONField(help_text='Estrutura Pydantic com justificativas e deduções brutas do Corretor.')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_results', to='orchestrator.executionsnapshot')),
            ],
            options={
                'verbose_name': 'Resultado do Corretor',
                'verbose_name_plural': 'Resultados dos Corretores',
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'auditor_type'), name='unique_auditor_per_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskexecution',
            constraint=models.CheckConstraint(condition=models.Q(('accumulated_cost_usd__gte', 0.0)), name='check_task_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='executionsnapshot',
            index=models.Index(fields=['task_execution', '-nash_score'], name='idx_rollback_optim'),
        ),
        migrations.AddConstraint(
            model_name='executionsnapshot',
            constraint=models.UniqueConstraint(fields=('task_execution', 'iteration_number'), name='unique_iteration_per_task'),
        ),
    ]
