# Generated by Django 5.2.17 on 2026-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='ID do modelo escolhido para esta execução (desacoplado do perfil).', max_length=100),
        ),
    ]
