# Generated by Django 5.2.17 on 2026-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_taskexecution_model_name_alter_taskexecution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em Execução'), ('COMPLETED', 'Concluído com Sucesso'), ('COMPLETED_WITH_ROLLBACK', 'Concluído com Rollback (Melhor Snapshot)'), ('ABORTED_GUARDRAIL_STRIKES', 'Abortado - Falha Crítica Guard-rail (3 Strikes)'), ('FAILED_BUDGET_EXCEEDED', 'Falha - Orçamento Excedido'), ('FAILED_TIMEOUT', 'Falha - Tempo Limite Excedido'), ('FAILED_NO_SNAPSHOTS', 'Falha - Estagnado sem Snapshots'), ('CANCELLED', 'Cancelado pelo Usuário')], default='PENDING', max_length=50),
        ),
    ]
